export const SET_CURRENT_INITIAL = "SET_CURRENT_INITIAL";
export const SET_CURRENT_AREA = "SET_CURRENT_AREA";
export const SET_CURRENT_GENDER = "SET_CURRENT_GENDER";
export const SET_OFFSET = "SET_OFFSET";
export const SET_SINER_LIST = "SET_SINER_LIST";
