//App.js
export const SET_TOP_LOADING = "SET_TOP_LOADING_";

export const SET_SEARCH_STATUS = "SET_SEARCH_STATUS";

export const SET_USER = "SET_USER";

export const SET_CURRENT_HEADER_INDEX = "SET_CURRENT_HEADER_INDEX";

export const SET_HEADER_STATUS = "SET_HEADER_STATUS";

export const SET_SCROLL_TOP = "SET_SCROLL_TOP";

export const SET_MIDDLE = "SET_MIDDLE";
